/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalht;
import java.sql.*;
import javax.swing.JOptionPane;
import koneksi.koneksi;


/**
 *
 * @author Pc
 */
public class Index extends javax.swing.JFrame {
    koneksi conn = new koneksi();;

    /**
     * Creates new form login
     */
    public Index() {
        initComponents();
        conn.ConnectToDB();
        conn.createAllTable();
        conn.data_admin();
        this.setLocationRelativeTo(null);
    }
    private void masuk(){
        try{
            String nama = user.getText();
            String passw = new String (pass.getPassword());
            conn.setStatement(conn.getConnect().createStatement());
            String sql = "Select * from user where username = '"+nama+"' And password = '"+passw+"'";
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            if(conn.getResultSet().next()){
                if(pass.getText().equals(conn.getResultSet().getString("password"))){
                    new Menu().show();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Password salah, silahkan coba lagi!!");
                    pass.setText("");
                    pass.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Login GAGAL!!");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        } finally { try{ conn.getResultSet().close(); conn.getPreStatement().close(); } catch(Exception e) { } }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 640));
        setSize(new java.awt.Dimension(960, 640));
        getContentPane().setLayout(null);

        user.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        user.setBorder(null);
        getContentPane().add(user);
        user.setBounds(480, 230, 390, 33);

        Login.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Login.setText("Login");
        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(500, 380, 110, 30);

        pass.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        pass.setBorder(null);
        getContentPane().add(pass);
        pass.setBounds(480, 310, 390, 33);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 0, 0);

        keluar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(750, 380, 100, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login form.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 642);

        setSize(new java.awt.Dimension(963, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

        masuk();
    }//GEN-LAST:event_LoginActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold> 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton keluar;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
