/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalht;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Pc
 */
public class lihatdata extends javax.swing.JFrame {

    /**
     * Creates new form lihatdata
     */
    koneksi conn = new koneksi();
    private String sql;
    private DefaultTableModel tab;
    public lihatdata() {
        initComponents();
        conn.ConnectToDB();
        createTable();
        getData();
    }
    
    
    public void createTable() {
        tab = new DefaultTableModel();
        Sis.setModel(tab);
        tab.addColumn("No.");
        tab.addColumn("ID_Peminjam");
        tab.addColumn("Nama");
        tab.addColumn("No KTP");
        tab.addColumn("Alamat");
        tab.addColumn("No HP");
        tab.addColumn("Lama Sewa");
        tab.addColumn("Mulai Sewa");
        tab.addColumn("Tanggal Pinjam");
        tab.addColumn("Banyak HT");
        tab.addColumn("DP");
    }
    
    public void getData() {
        tab.getDataVector().removeAllElements();
        tab.fireTableDataChanged();
        try {
            sql = "SELECT * FROM data_peminjaman order by id_peminjam asc";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            int i = 1;
            while (conn.getResultSet().next()) {
                Object[] isi = new Object[11];
                isi[0] = i + ".";
                isi[1] = conn.getResultSet().getString(1);
                isi[2] = conn.getResultSet().getString(2);
                isi[3] = conn.getResultSet().getString(3);
                isi[4] = conn.getResultSet().getString(4);
                isi[5] = conn.getResultSet().getString(5);
                isi[6] = conn.getResultSet().getString(6);
                isi[7] = conn.getResultSet().getString(7);
                isi[8] = conn.getResultSet().getString(8);
                isi[9] = conn.getResultSet().getString(9);
                isi[10] = conn.getResultSet().getString(10);
                tab.addRow(isi);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
        public void getData(String filter) {
        tab.getDataVector().removeAllElements();
        tab.fireTableDataChanged();
        try {
            sql = "SELECT * FROM data_peminjaman order by "+filter+" asc";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            int i = 1;
            while (conn.getResultSet().next()) {
                Object[] isi = new Object[11];
                isi[0] = i + ".";
                isi[1] = conn.getResultSet().getString(1);
                isi[2] = conn.getResultSet().getString(2);
                isi[3] = conn.getResultSet().getString(3);
                isi[4] = conn.getResultSet().getString(4);
                isi[5] = conn.getResultSet().getString(5);
                isi[6] = conn.getResultSet().getString(6);
                isi[7] = conn.getResultSet().getString(7);
                isi[8] = conn.getResultSet().getString(8);
                isi[9] = conn.getResultSet().getString(9);
                isi[10] = conn.getResultSet().getString(10);
                tab.addRow(isi);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Sis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        burut = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 642));
        setSize(new java.awt.Dimension(960, 642));
        getContentPane().setLayout(null);

        Sis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Sis);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 120, 570, 380);

        jLabel1.setText("Urutkan berdasarkan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(720, 90, 101, 20);

        burut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal masuk", "Nama" }));
        burut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burutActionPerformed(evt);
            }
        });
        getContentPane().add(burut);
        burut.setBounds(830, 90, 119, 20);

        Back.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(860, 10, 90, 37);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Lihat Datapenyewaan.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(4, 4, 960, 640);

        setSize(new java.awt.Dimension(960, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void burutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burutActionPerformed
        String urut=(String) burut.getSelectedItem();
        if(urut.equalsIgnoreCase("Tanggal Masuk")){
            getData("tanggal");
        }
        
        if(urut.equalsIgnoreCase("Nama")){
            getData("nama");
        }
    }//GEN-LAST:event_burutActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Menu().show();
     this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatdata().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background;
    private javax.swing.JTable Sis;
    private javax.swing.JComboBox<String> burut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
