/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalht;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Pc
 */
public class Peminjaman extends javax.swing.JFrame {
    /**
     * Creates new form Peminjaman
     */
    koneksi conn = new koneksi();
    function func = new function();
    private DefaultTableModel tab;
    
    
    private String hrg,nm,no,almt,nohpp,lm,ml,tgl,bykht,dpp,sql;
    private Object get_id;
    
    
    public Peminjaman() {
        initComponents();
        conn.ConnectToDB();
        createTable();
        getData();
        tanggal();
        jam();
    }
    
        
    public void createTable() {
        tab = new DefaultTableModel();
        Sis.setModel(tab);
        tab.addColumn("No.");
        tab.addColumn("ID_Peminjam");
        tab.addColumn("Nama");
        tab.addColumn("No KTP");
        tab.addColumn("Alamat");
        tab.addColumn("No HP");
        tab.addColumn("Lama Sewa");
        tab.addColumn("Mulai Sewa");
        tab.addColumn("Tanggal Pinjam");
        tab.addColumn("Banyak HT");
        tab.addColumn("DP");
    }
    
        public void getData() {
        tab.getDataVector().removeAllElements();
        tab.fireTableDataChanged();
        try {
            sql = "SELECT * FROM data_peminjaman order by id_peminjam asc";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            int i = 1;
            while (conn.getResultSet().next()) {
                Object[] isi = new Object[11];
                isi[0] = i + ".";
                isi[1] = conn.getResultSet().getString(1);
                isi[2] = conn.getResultSet().getString(2);
                isi[3] = conn.getResultSet().getString(3);
                isi[4] = conn.getResultSet().getString(4);
                isi[5] = conn.getResultSet().getString(5);
                isi[6] = conn.getResultSet().getString(6);
                isi[7] = conn.getResultSet().getString(7);
                isi[8] = conn.getResultSet().getString(8);
                isi[9] = conn.getResultSet().getString(9);
                isi[10] = conn.getResultSet().getString(10);
                tab.addRow(isi);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        }
  
    public void mauUpdate(){
        int row = Sis.getSelectedRow();
        get_id = tab.getValueAt(row, 1);
        try {
            sql = "SELECT * FROM data_peminjaman";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            while (conn.getResultSet().next()) {
                nama.setText(conn.getResultSet().getString(2));
                noktp.setText(conn.getResultSet().getString(3));
                alamat.setText(conn.getResultSet().getString(4));
                nohp.setText(conn.getResultSet().getString(5));
                lamasewa.setText(conn.getResultSet().getString(6));
                mulaisewa.setText(conn.getResultSet().getString(7));
                tanggal.setText(conn.getResultSet().getString(8));
                banyakht.setText(conn.getResultSet().getString(9));
                dp.setText(conn.getResultSet().getString(10));
            }
        } catch (Exception e) {
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        noktp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        lamasewa = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        banyakht = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sis = new javax.swing.JTable();
        back = new javax.swing.JButton();
        pilih = new javax.swing.JButton();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        mulaisewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 642));
        setSize(new java.awt.Dimension(960, 642));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 80, 50, 19);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("No KTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 120, 48, 19);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 160, 43, 19);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("No Hp");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 200, 38, 19);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setText("Lama Sewa");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 240, 73, 19);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setText("Mulai Sewa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 280, 71, 19);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setText("Banyak HT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 360, 69, 20);
        getContentPane().add(noktp);
        noktp.setBounds(600, 110, 222, 28);
        getContentPane().add(nama);
        nama.setBounds(600, 70, 222, 28);
        getContentPane().add(alamat);
        alamat.setBounds(600, 150, 222, 28);
        getContentPane().add(nohp);
        nohp.setBounds(600, 190, 222, 28);
        getContentPane().add(lamasewa);
        lamasewa.setBounds(600, 230, 89, 28);
        getContentPane().add(tanggal);
        tanggal.setBounds(600, 310, 220, 28);
        getContentPane().add(banyakht);
        banyakht.setBounds(600, 350, 222, 28);

        simpan.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(470, 430, 80, 23);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setText("Sudah dibayar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 400, 92, 19);
        getContentPane().add(dp);
        dp.setBounds(600, 390, 220, 28);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel11.setText("Hari");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 240, 30, 19);

        Sis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "No KTP", "Alamat", "No HP", "Lama Sewa", "Mulai Sewa", "Tanggal Pinjam", "Banyak HT", "Keterangan", "dp"
            }
        ));
        Sis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Sis);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(380, 460, 570, 170);

        back.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(870, 10, 80, 30);

        pilih.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        pilih.setText("Pilih");
        pilih.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        getContentPane().add(pilih);
        pilih.setBounds(650, 430, 80, 23);

        update.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        update.setText("Update");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(560, 430, 80, 23);

        hapus.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        hapus.setText("Refresh");
        hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(740, 430, 80, 23);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setText("/Jam");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(780, 270, 29, 19);
        getContentPane().add(mulaisewa);
        mulaisewa.setBounds(600, 270, 170, 28);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel13.setText("Tanggal Pinjam");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 320, 98, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penyewaanForm.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 640);

        setSize(new java.awt.Dimension(960, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    Calendar cal = Calendar.getInstance();
     private static final DateFormat sdf = new SimpleDateFormat("HH:mm:ss");
     private static final DateFormat sdt = new SimpleDateFormat("yyyy/MM/dd");
     public void jam(){
            String jam=new SimpleDateFormat("HH:mm:ss", Locale.FRANCE).format(new Date()); 
        mulaisewa.setText(jam);
        }
     public void tanggal(){
            String date=new SimpleDateFormat("dd/MM/YYYY", Locale.FRANCE).format(new Date()); 
        tanggal.setText(date);
    }
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        nm=nama.getText();
        no=noktp.getText();
        almt=alamat.getText();
        nohpp=nohp.getText();
        lm=lamasewa.getText();
        ml=(String)sdf.format(cal.getTime());
        tgl=(String)sdt.format(cal.getTime());
        bykht=banyakht.getText();
        dpp=dp.getText();
        try {   
            sql = "INSERT INTO data_peminjaman(id_peminjam, nama, noktp, "
                    + "alamat, nohp, lamasewa, mulaisewa, tanggal, banyakht, dp) "
                    + "VALUES ('" + func.getRandomChar() + "','" + nm + "','" + no + "',"
                    + "'" + almt + "','" + nohpp + "','" + lm + "','" + ml + "','" + tgl + "','" + bykht + "',"
                    + "'" + dpp + "')";
            conn.setStatement(conn.getConnect().createStatement());
            conn.getStatement().execute(sql);
            getData();
            JOptionPane.showMessageDialog(null,"berhasil disimpan");
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Maaf data anda tidak disimpan\n"
                + "error pada "+ e.getMessage());
        } finally { try{ conn.getResultSet().close(); conn.getPreStatement().close(); } catch(Exception e) { } }
    }//GEN-LAST:event_simpanActionPerformed
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      new Menu().show();
     this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String nm = String.valueOf(nama.getText());
        String Noktp = String.valueOf(noktp.getText());
        String Alamat = String.valueOf(alamat.getText());
        String Nohp = String.valueOf(nohp.getText());
        String Lamasewa = String.valueOf(lamasewa.getText());
        String Banyakht = String.valueOf(banyakht.getText());
        String Dp = String.valueOf(dp.getText());
        try {
            int row = Sis.getSelectedRow();
            get_id = tab.getValueAt(row, 1);
            sql = "UPDATE data_peminjaman SET nama='" + nm + "',noktp='" + Noktp + "',alamat='"
                    + Alamat + "' ,nohp='" + Nohp + "',lamasewa='" + Lamasewa + "',banyakht='" + Banyakht + ""
                    + "',dp='" + Dp + "' WHERE id_peminjam = '"+get_id+"'";
            conn.setStatement(conn.getConnect().createStatement());
            conn.getStatement().execute(sql);
            getData();
            JOptionPane.showMessageDialog(null, "Update Data Sukses");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data Gagal" + e.getMessage());
        } finally {
            try {
                conn.getResultSet().close();
                conn.getPreStatement().close();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        nama.setText("");
        noktp.setText("");
        alamat.setText("");
        nohp.setText("");
        lamasewa.setText("");
        mulaisewa.setText("");
        tanggal.setText("");
        banyakht.setText("");
        dp.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void SisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SisMouseClicked

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
        mauUpdate();
    }//GEN-LAST:event_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Sis;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton back;
    private javax.swing.JTextField banyakht;
    private javax.swing.JTextField dp;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lamasewa;
    private javax.swing.JTextField mulaisewa;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField noktp;
    private javax.swing.JButton pilih;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField tanggal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
