/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalht;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Pc
 */
public class Pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form Pengembalian
     */
    koneksi conn = new koneksi();
    Calendar cal = Calendar.getInstance();
    private static final DateFormat sdf = new SimpleDateFormat("HH:mm:ss");
    private static final DateFormat sdt = new SimpleDateFormat("yyyy/MM/dd");
    String harg = "25000";
    String dend = "25000";
    private String nm,tlt,sql;
    private String banyak;
    private Object get_id;

    private DefaultTableModel tab;
    public Pengembalian() {
        initComponents();
        conn.ConnectToDB();
        createTable();
        getData();
        tanggal2();
    }
    
    public void createTable() {
        tab = new DefaultTableModel();
        Sis.setModel(tab);
        tab.addColumn("No.");
        tab.addColumn("ID_Peminjam");
        tab.addColumn("Nama");
        tab.addColumn("No KTP");
        tab.addColumn("Alamat");
        tab.addColumn("No HP");
        tab.addColumn("Lama Sewa");
        tab.addColumn("Mulai Sewa");
        tab.addColumn("Tanggal Pinjam");
        tab.addColumn("Banyak HT");
        tab.addColumn("DP");
    }
    
        public void getData() {
        tab.getDataVector().removeAllElements();
        tab.fireTableDataChanged();
        try {
            sql = "SELECT * FROM data_peminjaman order by id_peminjam asc";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            int i = 1;
            while (conn.getResultSet().next()) {
                Object[] isi = new Object[11];
                isi[0] = i + ".";
                isi[1] = conn.getResultSet().getString(1);
                isi[2] = conn.getResultSet().getString(2);
                isi[3] = conn.getResultSet().getString(3);
                isi[4] = conn.getResultSet().getString(4);
                isi[5] = conn.getResultSet().getString(5);
                isi[6] = conn.getResultSet().getString(6);
                isi[7] = conn.getResultSet().getString(7);
                isi[8] = conn.getResultSet().getString(8);
                isi[9] = conn.getResultSet().getString(9);
                isi[10] = conn.getResultSet().getString(10);
                tab.addRow(isi);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mulaisewa = new javax.swing.JTextField();
        Lamasewa = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tampil = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sis = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        banyakht = new javax.swing.JTextField();
        denda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tanggal2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(960, 642));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 70, 70, 19);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Mulai Sewa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 150, 90, 19);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Pinjam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 190, 110, 19);

        mulaisewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaisewaActionPerformed(evt);
            }
        });
        getContentPane().add(mulaisewa);
        mulaisewa.setBounds(530, 140, 303, 28);

        Lamasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamasewaActionPerformed(evt);
            }
        });
        getContentPane().add(Lamasewa);
        Lamasewa.setBounds(530, 260, 128, 30);
        getContentPane().add(tanggal);
        tanggal.setBounds(530, 180, 303, 28);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(530, 60, 303, 28);
        getContentPane().add(harga);
        harga.setBounds(530, 380, 303, 30);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 390, 70, 19);

        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        getContentPane().add(totalharga);
        totalharga.setBounds(530, 460, 303, 31);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setText("Total Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 470, 90, 19);

        Tampil.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Tampil.setText("Tampil");
        Tampil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilActionPerformed(evt);
            }
        });
        getContentPane().add(Tampil);
        Tampil.setBounds(850, 350, 90, 30);

        hapus.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(850, 390, 90, 30);

        back.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(875, 3, 80, 30);

        Sis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "No KTP", "Alamat", "No HP", "Lama Sewa", "Mulai Sewa", "Banyak HT", "Keterangan", "DP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Sis);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(379, 504, 570, 130);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel8.setText("Banyak HT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 110, 90, 19);

        banyakht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banyakhtActionPerformed(evt);
            }
        });
        getContentPane().add(banyakht);
        banyakht.setBounds(530, 100, 120, 30);

        denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dendaActionPerformed(evt);
            }
        });
        getContentPane().add(denda);
        denda.setBounds(530, 340, 303, 30);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel9.setText("Denda");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 350, 70, 19);
        getContentPane().add(tanggal2);
        tanggal2.setBounds(530, 220, 303, 29);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal Pengembalian");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 230, 150, 19);
        getContentPane().add(telat);
        telat.setBounds(530, 300, 128, 30);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel11.setText("Terlambat");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 310, 90, 19);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Lama Sewa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 270, 90, 19);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel13.setText("Hari");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(670, 270, 60, 19);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel14.setText("Hari");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(670, 310, 60, 19);
        getContentPane().add(dp);
        dp.setBounds(530, 420, 303, 30);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setText("Yang sudah dibayar");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(380, 430, 130, 19);

        refresh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(850, 430, 90, 30);

        BACKGROUND.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pengembalianForm.png"))); // NOI18N
        getContentPane().add(BACKGROUND);
        BACKGROUND.setBounds(0, 0, 960, 640);

        setSize(new java.awt.Dimension(960, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


 

     public void tanggal2(){
         String date = new SimpleDateFormat("dd/MM/YYYY", Locale.FRANCE).format(new Date());
         tanggal2.setText(date);
    }
     
    private void TampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilActionPerformed
        int row = Sis.getSelectedRow();
        get_id = tab.getValueAt(row, 1);
        try {
            sql = "SELECT * FROM data_peminjaman WHERE id_peminjam = '"+get_id+"'";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            while (conn.getResultSet().next()) {
                nama.setText(conn.getResultSet().getString(2));
                banyakht.setText(conn.getResultSet().getString(9));
                mulaisewa.setText(conn.getResultSet().getString(7));
                tanggal.setText(conn.getResultSet().getString(8));
                tanggal2.setText(sdt.format(cal.getTime()));
                Lamasewa.setText(conn.getResultSet().getString(6));
                tlt = telat.getText();
                int aa = Integer.parseInt(telat.getText());
                int dnd = aa * Integer.parseInt(dend);
                denda.setText("" + dnd);
                harga.setText(harg);
                dp.setText(conn.getResultSet().getString(10));
                int a1 = Integer.parseInt(conn.getResultSet().getString(9));
                int a2 = Integer.parseInt(conn.getResultSet().getString(10));
                int tot = (a1 * Integer.parseInt(harg)) + dnd - a2;
                totalharga.setText("" + tot);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Harap Isi Terlambat Harinya terlebih dahulu");
            System.out.println(e);
        }
       
    }//GEN-LAST:event_TampilActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            int row = Sis.getSelectedRow();
            get_id = tab.getValueAt(row, 1);
            conn.setStatement(conn.getConnect().createStatement());
            String sql = "DELETE FROM data_peminjaman WHERE id_peminjam = '"+get_id+"'";
            conn.getStatement().executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "BERHASIL BERSIHKAN", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "GAGAL BERSIHKAN", "Informasi", JOptionPane.ERROR_MESSAGE);
        }
        nama.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void LamasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamasewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LamasewaActionPerformed

    private void mulaisewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaisewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulaisewaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     new Menu().show();
     this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void banyakhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banyakhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banyakhtActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dendaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_dendaActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        nama.setText("");
        banyakht.setText("");
        mulaisewa.setText("");
        tanggal.setText("");
        tanggal2.setText("");
        Lamasewa.setText("");
        telat.setText("");
        denda.setText("");
        harga.setText("");
        dp.setText("");
        totalharga.setText("");
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JTextField Lamasewa;
    private javax.swing.JTable Sis;
    private javax.swing.JButton Tampil;
    private javax.swing.JButton back;
    private javax.swing.JTextField banyakht;
    private javax.swing.JTextField denda;
    private javax.swing.JTextField dp;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mulaisewa;
    private javax.swing.JTextField nama;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tanggal2;
    private javax.swing.JTextField telat;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
